### ISSUE TITLE
Error: Invalid or empty translations

### ISSUE THREAD

**Issue by kizule** [Vikipolimer/Adiutor#11]
Looks like I made a mistake, and Adiutor isn't loading on Serbian Wikipedia for me at all.
This is happening since I've updated translations on the wiki. The cleanup of translations for the Serbian language, which I made on https://translatewiki.net will be probably committed later by @translatewiki.

This is error from the browser console:

```js
Error fetching and processing translations: Error: Invalid or empty translations
    at css (ext.gadget.Adiutor-script-0.js:145:9)
    at runScript (startup.js:1255:7)
    at Array.<anonymous> (startup.js:1333:6)
    at flushCssBuffer (startup.js:586:28)
```

**Comment by doguabaris** [comment]
Yesterday you asked me for a merge request to delete this file, which I did, and now I will undo it.

**Comment by doguabaris** [comment]
Yesterday you asked me for a merge request to delete this file, which I did, and now I will undo it.

**Comment by kizule** [comment]
> Yesterday you asked me for a merge request to delete this file, which I did, and now I will undo it.

That's not making this issue. sr.json shouldn't exist, because sr is fallback to sr-ec, and sr-ec.json exists.

**Comment by kizule** [comment]
I think that the issue is with gadget not falling back to the English language, if translation doesn't exist.

**Comment by kizule** [comment]
Or my changes at https://sr.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D1%98%D0%B0%D0%B2%D0%B8%D0%BA%D0%B8:Gadget-Adiutor-i18.json

Update: I've reverted them.

**Comment by doguabaris** [comment]
Oh, you need to keep en anyway.

**Comment by doguabaris** [comment]
> Or my changes at https://sr.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D0%B8%D1%98%D0%B0%D0%B2%D0%B8%D0%BA%D0%B8:Gadget-Adiutor-i18.json
> 
> Update: I've reverted them.

Or you can just update Adiutor with version 2.0.0

**Comment by kizule** [comment]
I'm updating Adiutor on wiki now, will keep you updated.

**Comment by kizule** [comment]
Well, I've updated everything, and I'm hoping that I haven't done something wrong, as Adiutor isn't still appearing for me, although I've enabled it in the settings.

**Comment by kizule** [comment]
https://sr.wikipedia.org/wiki/%D0%9F%D0%BE%D1%81%D0%B5%D0%B1%D0%BD%D0%BE:%D0%A1%D0%B2%D0%B5_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5?from=Gadget-Adiutor&to=Gadget-B&namespace=8
