### ISSUE TITLE
Trailing whitespace in message "hello"

### ISSUE THREAD

**Issue by Nikerabbit** [Vikipolimer/Adiutor#8]
Trailing whitespace is not supported in MediaWiki. Can you please remove the space?

**Comment by doguabaris** [comment]
@Nikerabbit Are you referring to trailing whitespace in translations?

**Comment by Nikerabbit** [comment]
In the English source language.

**Comment by doguabaris** [comment]
@Nikerabbit  Fixed, thanks for feedback.
