### ISSUE TITLE
Old user settings should be cleaned up after migration

### ISSUE THREAD

**Issue by vlakoff** [Vikipolimer/Adiutor#9]
On [frwiki](https://fr.wikipedia.org/), I had previously run Adiutor (version 1.2.4).

Running `mw.user.options.get();`, I see Adiutor has set 3 items:

* `gadget-Adiutor`: a single 1 or 0 digit (not set by Adiutor, it is a MediaWiki setting).
* `userjs-adiutor`: a JSON object, which is less than a kilobyte.
* `userjs-adiutor-i18-translations`: a **huge** JSON object, which is dozens of kilobytes.

I have just run again Aditor, which meanwhile has been updated to version 1.2.5 (see notably [this file update](https://fr.wikipedia.org/w/index.php?title=MediaWiki:Gadget-Adiutor.js&diff=prev&oldid=207661804)). There are 2 new items:

* `userjs-adiutor-frwiki`: migrated from `userjs-adiutor` (same data, except `adiutorVersion` property).
* `userjs-adiutor-i18-fr`: migrated from `userjs-adiutor-i18-translations` (`fr` property of previous item, i.e. same data minus a little metadata).

Problem is, the old items haven't been cleaned up. This is particularly a problem with `userjs-adiutor-i18-translations`, which is huge and included in the HTML of every pageview.

Note that there is a major issue currently: these items cannot be deleted. For now, the best we can do is to set them to empty values. See [Setting global preferences and local overrides](https://www.mediawiki.org/wiki/Extension:GlobalPreferences/API#Setting_global_preferences_and_local_overrides
) and [T207448](https://phabricator.wikimedia.org/T207448).

By the way, as I stated above, the items are included in the HTML of every pageview. For `userjs-adiutor-i18-fr` (which is a data cache), a much, much better option would be to use [mediawiki.storage](https://www.mediawiki.org/wiki/ResourceLoader/Core_modules#mediawiki.storage). (also, this would let it have an expiry time; currenly, once the translation cache has been set, it is only updated, executing `updateTranslations()`, when a new default user option is found… which is unrelated.)

**Comment by doguabaris** [comment]
Hey, sorry for the late reply, I’ll take care of it soon.

**Comment by vlakoff** [comment]
Btw, if the options are set to empty strings, the following `JSON.parse('')` calls would trigger JavaScript errors.

A possible fix would be to replace for example:
```js
JSON.parse(mw.user.options.get(wikiOptions));
```
With:
```js
JSON.parse(mw.user.options.get(wikiOptions) || null);
```

Or even better, `JSON.parse()` calls should be put in "try/catch" blocks, to safeguard against any invalid JSON string.

**Comment by vlakoff** [comment]
As examples, see what MediaWiki does, [here](https://github.com/wikimedia/mediawiki/blob/e828301de4f7eb70ce29fea9db0353ae789547c7/resources/src/mediawiki.rcfilters/Controller.js#L276-L280) or [here](https://github.com/wikimedia/mediawiki/blob/e828301de4f7eb70ce29fea9db0353ae789547c7/resources/src/startup/mediawiki.loader.js#L1924-L1947).

For Adiutor, I could suggest:

```js
try {
    var messages = JSON.parse(adiutorUserInterfaceTranslations);
} catch (e) {}

if (typeof messages !== 'object' || messages === null || Array.isArray(messages) || Object.keys(messages).length === 0) {
    throw new Error('Invalid or empty translations');
}

// alternative, inspired by:
// https://stackoverflow.com/questions/65787971/ways-to-determine-if-something-is-a-plain-object-in-javascript
if (!messages || messages.constructor !== Object || Object.keys(messages).length === 0) {
    throw new Error('Invalid or empty translations');
}

```

Notes:

- Arrays also have type "object". And it could easily be overlooked, as `Object.keys(['foo', 'bar']).length` gives 2 (!== 0).
- `null` also has type "object"! And `Object.keys(null)` triggers a JavaScript error…
- In practice, arrays shouldn't be encountered, but `null` could easily be encountered, if the option is not found.
- Alternatively, [`$.isPlainObject()`](https://api.jquery.com/jQuery.isPlainObject/) ([code](https://github.com/jquery/jquery/blob/1ad66aeb6d7d94f8e4c8e2286569722ca41f9868/src/core.js#L201)) could be used. Actually, I think this would be the best solution.

**Comment by doguabaris** [comment]
I made the necessary updates. Thank you.
